empty
DominikK03/Social_Forum pull request #20
Opened 2024-10-30 09:57 UTC by DominikK03

2024-10-30 10:01 UTC, krzysztofsurdy-htg commented on .gitattributes
> +* text=auto
test

2024-10-30 11:01 UTC, krzysztofsurdy-htg requested changes

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on .gitattributes
> +# Auto detect text files and perform LF normalization
❓What this file does? Why is it needed?

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on .gitignore
> +/vendor
🔧 .idea should be added here. There is no need to commit the .idea content since its from IDE.
Also stuf like .DS_store should be added.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on composer.json
> +        "psr/container": "^2.0",
You can add php version requirement here since you have syntax that can run only above specific version.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on docker-compose.yml
> +      - ./storage/mysql:/var/lib/mysql
Create virtual volume here. Docker DB volume mount shouldnt be kept inside project.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on docker-compose.yml
> +      - 8000:80
You can add depends on: between containers. For example there is no point of running nginx if app container fails to start.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on docker/nginx/nginx.conf
> +    location ~* \.(gif|jpg|jpeg|png)$ {
All of these should be merged under one location that points to public

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/index.php
> +$request = new Request($_SERVER['REQUEST_URI'], $_SERVER['REQUEST_METHOD'], $_POST, $_GET, $_FILES, $_SESSION);
Instead of passing it like that. You can create RequestFactory that has static method createFromGlobals(), or add it to Request class.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/index.php
> +$requestValidator = new RequestValidator($request);
Why request object needs to be created? Cant it be called through static method RequestValidator::validate($request)?
Plus it could be done in the RequestFactory method.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on .gitignore
> +/vendor
Also files from public /images/avatar and common stuff thats uploaded by user and is dynamic should be ignored.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/AccountEdit.js
> +$(document).ready(function () {
You can create small class out of it and on document ready you can call like Main.init() instead. It will be much cleaner.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/AccountEdit.js
> +    $('.change-password-btn').click(function () {
You can set DOM elements like $('.change-password-btn') to variable. It will be way cleaner.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/AccountEdit.js
> +        $('#newPassword, #confirmPassword').removeClass('is-invalid is-valid');
All of calls like that could be placed in functions like hideFeedbackStatus().
In general no function should be longer than lets say 15 lines.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/Admin.js
> +                    console.log(response);
Console.log left

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/AccountEdit.js
> +                    console.log(response);
console.log left

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/AccountEdit.js
> +                console.log(response)
console.log left

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/Admin.js
> +                console.log(response)
In general there is plenty of console.log left XD

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on public/storage/js/getComment.js
> +$(document).ready(function () {
As said. All of this JS files can be placed within single JS file thats inquired on main page. And you then base on function calls.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AccountController.php
> +#[AllowDynamicProperties] class AccountController
Attribute shouldnt be the same line as class declaration. It should be one line above.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AccountController.php
> +            $accountView = new AccountView($accountInfoView, $navbarView);
That could be moved to some ViewFactory, where you have different methods like createNavBarView(), createAccountView().

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AccountController.php
> +                '{{CreatedAt}}' => $request->getUserSession()['createdAt']->format("Y-m-d H:i:s"),
Operators {{}} should be added by HTML parser, shouldnt be present when parsing data.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AccountController.php
> +            return new RedirectResponse('/', ['loginStatus' => 'not-logged-in']);
Login status can be placed to Enum/consts.
In general this can be moved to NotLoggedInRedirectResponse.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AccountController.php
> +            return new JsonResponse(['success' => true]);
This can be moved to SuccessfullResponse

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AccountController.php
> +            return new JsonResponse(['success' => false, 'message' => 'Invalid password']);
This can be moved to InvalidPasswordResponse

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AccountController.php
> +                    "avatar-" . $request->getUserSession()['username'] . "."
Parsing name should be done in service. You can add method like createAvatarImage.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/AuthController.php
> +        if (session_status() === PHP_SESSION_NONE) {
This should be moved to SessionManager to function like startSession()

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/MainPageController.php
> +require '../vendor/autoload.php';
Require autoload. Isnt it development leftover?

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/MainPageController.php
> +        ImageService             $imageService,
In general there should be single space between type and variable name, you need to change your phpstorm style config.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/PostPageController.php
> +    #[Route('/post/postComment', 'POST', [Role::user, Role::admin, Role::master])]
You should make, it a bit different that lower roles include previous ones. So Role master would include all the roles. Admin would include admin and user. So there would be no need to write down all the roles that can access route.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Controller/PostPageController.php
> +        $this->adminService->adminRepository->deleteCommentByID($request->getCommentID());
You shouldnt access the admin repository straight like that. It should go through admin service through function call.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Core/DI/Container.php
> +                    throw new \Exception("Cannot build");
You should create dedicated exception for it ContainerCannotBuildGenericException

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Core/DI/Exception/ClassNotFoundException.php
> +    protected $message = 'Class not found in Container';
Its done bit differently, because during calling new ClassNotFoundException() I still can change your message.

It should be done through constructor with parent construct call.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Core/HTTP/Exception/RouteNotFoundException.php
> +
You have plenty of empty lines that are not needed through out the repo.
Also each file should have empty line at the end of it, even github screams about it.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Core/HTTP/Response/JsonResponse.php
> +        $jsonData = json_encode($data);
Whats the point of variable? You can do it straight in parent construct call

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Core/HTTP/Response/Response.php
> +        http_response_code($this->statusCode);
Stuff like that shouldnt be done in response. It should be done in kernel after handling request.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Enum/Role.php
> +    public static function fromName(string $name): ?self {
There is from() function within enum, whats the point of this function?

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Kernel.php
> +#[AllowDynamicProperties]
What this attribute does? I can see it pretty often.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Kernel.php
> +                if (method_exists($dedicatedRequest, 'fromRequest')) {
fromRequest string should go to const

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Model/Image.php
> +    public function __construct(private string $imageName,
When you have such class where operation on variable is not performed, you can change class to readonly and set promoted properties scope to public.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/MysqlClient.php
> +            $this->pdo = new PDO(
This should go to factory class, like PDOConnectionFactory.
Also config could be made into class PDOConnectionConfig with interface ConnectionConfig

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/MysqlClient.php
> +class MysqlClient implements MysqlClientInterface
`This` should be named PDOMysqlClient.
And shouldnt be placed directly in src.
The only class that can be directly in src is Kernel

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Query.php
> +        $wherePart = count($this->wheres) > 0 ? ' WHERE ' . implode(' AND ', $this->wheres) : '';
Take a look at sprintf() php function

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Repository/Account/AccountRepository.php
> +#[AllowDynamicProperties] class AccountRepository implements AccountRepositoryInterface
The idea is That AccountRepositoryInterface declares the methods, while implementations are per storage. So this class should be named MysqlAccountRepository.
This approach is called Adapter.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Repository/Image/ImageRepository.php
> +        move_uploaded_file(
You could create FileSystemClient for such operations and use it here

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Repository/Image/ImageRepository.php
> +class ImageRepository implements ImageRepositoryInterface
This should be named FileSystemImageRepository

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Repository/Post/PostRepository.php
> +            ->select(
Select claim array of strings, not single string.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Repository/Post/PostRepository.php
> +        $this->client->pushWithoutResults($builder->getInsertQuery());
Whats the point of having separate methods for push without/with result?
It can be just named persist() and never return. If you need results, you should fetch them separately.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Repository/Post/PostRepository.php
> +        return $this->client->rowCount($builder->getSelectQuery());
There is no point in having rowCount in client. You can remove this function and just fetch results and count them. Same result, one less method.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Request/AccountRequest.php
> +        if ($this->request->getMethod() == "POST") {
Whats the point of checking http method?
Instead of all this IFs you can just use assertion class and make like  assertKeysExist()

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Request/CommentRequest.php
> +        $this->username = $this->request->getSessionParam('user', 'username');
params like 'user' and 'username' should go to consts

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Request/CommentRequest.php
> +        return json_decode(file_get_contents("php://input"), true)['comment_id'];
Shouldnt this be a part of parent class?
Also why do you use php input here

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/RequestValidator.php
> +        return $this->request->getSessionParam('user', 'userid') == $resourceOwnerID;
Do not be affraid of using consts, they are there for you not to repeat strings over and over again

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Service/Auth/AuthService.php
> +        $_SESSION['user'] = [
You shouldnt be using global variables outside Request and SessionManager

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Service/Post/PostService.php
> +        ?string $postContent,
If null is allowed to be given its a good practice to give null as default value.
And other way around, you can give ?Image since you have null default value.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Util/StaticValidator.php
> +    public static function assertEmailExists(string $email, ?array $users)
StaticValidator shouldnt have logic dedicated methods.
StaticValidator is generic class and should have only generic methods like assertKeyExists, assertGreaterThan etc.

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Util/StaticValidator.php
> +    public static function verifyLoginRequest(?object $user, string $username, string $password, ?string $passwordHash)
Stuff like that should be in class like AuthService

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Util/TemplateRenderer.php
> +        $template = file_get_contents(TEMPLATE_PATH . '/' . $html);
You can use FileSystem instead of using file_get_contents everywhere

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/Util/TemplateRenderer.php
> +    public function renderPosts(string $html, array $data): string
TemplateRendered shouldnt have methods like renderPost/s.

Its generic logic, dedicated render should be done through View using templates

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/View/Admin/AdminPanelView.php
> +            '{{Navbar}}' => $this->navbarView->renderWithRenderer($renderer)
'navbar' instead of '{{Navbar}}'

2024-10-30 11:01 UTC, krzysztofsurdy-htg commented on src/View/Admin/AdminPostView.php
> +        return $renderer->renderPostsAsAdmin('post/post.html', $this->data);
template name to const

2025-02-20 12:44 UTC, DominikK03 commented on src/Request/AccountRequest.php
> +        if ($this->request->getMethod() == "POST") {
Using an assertion class is useful when all required keys must exist, but in this case, different fields might be present depending on the request's purpose.

2025-02-20 15:48 UTC, merged